//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciNotMvc.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLNOTLAR
    {
        public int NotID { get; set; }
        public Nullable<byte> DersID { get; set; }
        public Nullable<int> OgrID { get; set; }
        public Nullable<byte> Sınav1 { get; set; }
        public Nullable<byte> Sınav2 { get; set; }
        public Nullable<byte> Sınav3 { get; set; }
        public Nullable<byte> Proje { get; set; }
        public Nullable<decimal> Ortlama { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual TBLDERSLER TBLDERSLER { get; set; }
        public virtual TBLOGRENCİLER TBLOGRENCİLER { get; set; }
    }
}
